# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
project_name: ghorg
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ghorg
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
archives:
  - id: ghorg
    name_template: >-
      {{- .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: "checksums.txt"
changelog:
  disable: true

dockers_v2:
  - images:
      - "ghcr.io/blairham/ghorg"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Quickly clone an entire org/users repositories into one directory"
      "org.opencontainers.image.url": "https://github.com/blairham/ghorg"
      "org.opencontainers.image.source": "https://github.com/blairham/ghorg"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
    extra_files:
      - sample-conf.yaml
      - sample-reclone.yaml

homebrew_casks:
  - repository:
      owner: blairham
      name: homebrew-utils
      branch: master

    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/blairham/ghorg"

    description: "Quickly clone an entire org/users repositories into one directory"

    binaries:
      - ghorg

    caveats: |
      For examples on how to use ghorg see: https://github.com/blairham/ghorg/tree/master/examples

      Remember to set your $HOME/.config/ghorg/conf.yaml

      Here's all you need to do...
      1) mkdir -p $HOME/.config/ghorg
      2) curl https://raw.githubusercontent.com/blairham/ghorg/master/sample-conf.yaml > $HOME/.config/ghorg/conf.yaml
